start1:
	dotnet run db_cp.csproj --urls "http://host.docker.internal:5561"

start2:
	dotnet run db_cp.csproj --urls "http://host.docker.internal:5562"
	
start3:
	dotnet run db_cp.csproj --urls "http://host.docker.internal:5563"
	
start-mirror:
	dotnet run db_cp.csproj --urls "http://host.docker.internal:5565"
