CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Agent" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerId" integer NOT NULL,
    "Surname" text NOT NULL,
    "Country" text NOT NULL,
    CONSTRAINT "PK_Agent" PRIMARY KEY ("Id")
);

CREATE TABLE "Club" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Country" text NOT NULL,
    "FoundationDate" bigint NOT NULL,
    CONSTRAINT "PK_Club" PRIMARY KEY ("Id")
);

CREATE TABLE "Coach" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Surname" text NOT NULL,
    "Country" text NOT NULL,
    "WorkExperience" bigint NOT NULL,
    CONSTRAINT "PK_Coach" PRIMARY KEY ("Id")
);

CREATE TABLE "Player" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClubId" integer NOT NULL,
    "Surname" text NOT NULL,
    "Rating" bigint NOT NULL,
    "Country" text NOT NULL,
    "Price" bigint NOT NULL,
    CONSTRAINT "PK_Player" PRIMARY KEY ("Id")
);

CREATE TABLE "Squad" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CoachId" integer NOT NULL,
    "Name" text NOT NULL,
    "Rating" bigint NOT NULL,
    CONSTRAINT "PK_Squad" PRIMARY KEY ("Id")
);

CREATE TABLE "SquadPlayer" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SquadId" integer NOT NULL,
    "PlayerId" integer NOT NULL,
    CONSTRAINT "PK_SquadPlayer" PRIMARY KEY ("Id")
);

CREATE TABLE "User" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Login" text NOT NULL,
    "Password" text NOT NULL,
    "Permission" text NOT NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230109180424_initial', '6.0.0');

COMMIT;

